### ISSUE TITLE
Helm version gets wrong rendered in timoni

### ISSUE THREAD

**Issue by suse-coder** [stefanprodan/flux-aio#110]
When I install this helm release with flux-helm-release then it gets rendered as a different version (so instead of 0.10.1 it renderes as   lastAttemptedRevision: 0.10.1+53d9c5dffd49 that then fails:
```
host: synapse.services.services.test
status:
  conditions:
  - lastTransitionTime: "2025-04-16T15:46:25Z"
    message: Running 'install' action with timeout of 1h0m0s
    observedGeneration: 1
    reason: Progressing
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2025-04-16T15:46:25Z"
    message: Running 'install' action with timeout of 1h0m0s
    observedGeneration: 1
    reason: Progressing
    status: Unknown
    type: Ready
  lastAttemptedConfigDigest: sha256:e96eb8f79c9acb59507a1f2b7c1f6868f3d3a0c213550afd75fb470a5a841d61
  lastAttemptedGeneration: 1
  lastAttemptedRevision: 0.10.1+53d9c5dffd49
  lastAttemptedRevisionDigest: sha256:53d9c5dffd491da66966f18c45100f285eee264666b1786b8fb250aea2997eb1
  observedGeneration: -1
```

The error is:
```
  Warning  InstallFailed  15s  helm-controller  Helm install failed for release element/matrix-stack with chart matrix-stack@0.10.1+53d9c5dffd49: 1 error occurred:
           * ConfigMap "matrix-stack-well-known-haproxy" is invalid: metadata.labels: Invalid value: "0.10.1+53d9c5dffd49": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

```
bundle: {
  apiVersion: "v1alpha1"
  name:       "ess-matrix-stack-bundle"
  instances: {
    "matrix-stack": {
      module: {
        url:     "oci://ghcr.io/stefanprodan/modules/flux-helm-release"
        version: "latest"
      }
      namespace: "element"
      values: {
        repository: {
          url: "oci://ghcr.io/element-hq/ess-helm"
        }
        chart: {
          name:    "matrix-stack"
          version: "0.10.1"
        }


        sync: {
          timeout: 60
        }

        helmValues: {
          serverName: string @timoni(runtime:string:WELLKNOWN_NAME)

          synapse: {
            ingress: {
              host: string @timoni(runtime:string:SNYAPSE_URL)
            }   
          }

          matrixAuthenticationService: {
            ingress: {
              host: string @timoni(runtime:string:MATRIXAUTH_URL)
            }
          }

          matrixRTC: {
            ingress: {
              host: string @timoni(runtime:string:MATRIXRTC_URL)
            }
          }

          elementWeb: {
            ingress: {
              host: string @timoni(runtime:string:ELEMENT_URL)
            }
          }

          postgres: {
            enabled: true
            storage: {
              size: "10Gi"
            }
          }

        }
      }
    }
  }
}

```

how can i force timoni bundle to just use that version?
