### ISSUE TITLE
How to use basic auth for private git repo in flux-git-sync 

### ISSUE THREAD

**Issue by codering** [stefanprodan/flux-aio#90]
I have a private git repo and no token read it,  only have username and password.

**Comment by codering** [comment]
```yaml
bundle: {
    _token:   string @timoni(runtime:string:DEPLOY_TOKEN)
    apiVersion: "v1alpha1"
    name:       "podinfo"
    instances: {
        "podinfo": {
            module: url: "oci://ghcr.io/stefanprodan/modules/flux-git-sync"
            namespace: "flux-system"
            values: {
                git: {
                    url:   "https://" + _token + "@your-git-repo"
                    ref:   "refs/heads/master"
                    path:  "./demo"
                }
                sync: targetNamespace: "default"
            }
        }
    }
}
```
